apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30001
  selector:
    app.kubernetes.io/name: traefik
