apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-css
spec:
  provider:
    vault:
      server: "http://vault.vault:8200"
      path: "k8s/"
      version: "v2"
      auth:
        appRole:
          path: "approle"
          roleId: "a9c54320-75a3-07a9-c809-1bcab58fea4c"
          secretRef:
            name: "k8s-secret-injector"
            namespace: "external-secrets"
            key: "secret-id"
